name: myapp

# --- Services --- #

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  authservice:
    networks:
      - rabbitmq_net
      - dataservices_net
    depends_on:
      - rabbitmq
    restart: on-failure
    image: d3akhtar/authservice
    ports:
      - 8080:8080

  counterrangerpcserver:
    networks:
      - rabbitmq_net
    environment:
      - DOTNET_ENVIRONMENT=Production
    depends_on:
      - rabbitmq
    restart: on-failure
    image: d3akhtar/counterrangerpcserver
    ports:
      - 8081:8080
  
  shorturlservice:
    networks:
      - rabbitmq_net
      - dataservices_net
    image: d3akhtar/shorturlservice
    depends_on:
      - rabbitmq
    restart: on-failure
    ports:
      - 8082:8080

  usershorturlservice:
    networks:
      - rabbitmq_net
      - dataservices_net
    image: d3akhtar/usershorturlservice
    depends_on:
      - rabbitmq
      - authservice
    restart: on-failure
    ports:
      - 8083:8080

# --- Networks --- #

networks:
  rabbitmq_net:
    driver: bridge
  dataservices_net:
    driver: bridge

# --- Volumes --- #